apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sd67r9pbf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sd67r9pbf-nodejs 
  name: sd67r9pbf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: sd67r9pbf-nodejs 
